### ISSUE TITLE
plpgsql

### ISSUE THREAD

**Issue by abgit** [asio/otp#1]
Hi @asio ,

This could be much better if implemented in `plpgsql` only ( instead of a mix of `plpgsql` and `plperlu` ).
Is it possible?

best,

**Comment by asio** [comment]
Probably, but it will require a rewrite of the functions pack/unpack and hmac in plgpsql

**Comment by abgit** [comment]
seems that,
- `hmac()` is provided by [pgcrypto](http://www.postgresql.org/docs/current/static/pgcrypto.html)
- there are some perl `pack()` [ideas](http://www.postgresql.org/message-id/7216CCB6-CDA2-4E1B-9BDE-ECD912CD7854@unicell.co.il)
- not sure if unpack can be implemented as some reverse of previous pack
